import { TemplateConfig } from '@/types/template';
import { TEMPLATE_CONFIGS as EXISTING_CONFIGS, getTemplateConfig as getExistingConfig } from './configs';

/**
 * ALL 50 TEMPLATE CONFIGURATIONS
 * This file contains the complete set of template configurations
 */

// Import existing configs (corp-01 to tech-13)
const BASE_CONFIGS = EXISTING_CONFIGS;

// Add remaining configurations
const ADDITIONAL_CONFIGS: Record<string, TemplateConfig> = {
    // TECH 14-20 (7 more)
    'tech-14': { id: 'tech-14', colors: { primary: '#1e293b', secondary: '#475569', accent: '#06b6d4', text: '#334155', textLight: '#64748b', background: '#ffffff', border: '#e2e8f0' }, fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'minimal', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '4px' }, icons: { show: true, style: 'outline' } },
    'tech-15': { id: 'tech-15', colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#60a5fa', text: '#1f2937', textLight: '#6b7280', background: '#f9fafb', border: '#d1d5db' }, fonts: { heading: 'Roboto Mono, monospace', body: 'Roboto, sans-serif', size: { name: '30px', heading: '17px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '22px', item: '13px', margin: '42px', padding: '15px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '2px', radius: '6px' }, icons: { show: true, style: 'solid' } },
    'tech-16': { id: 'tech-16', colors: { primary: '#1e3a8a', secondary: '#1e40af', accent: '#3b82f6', text: '#1e293b', textLight: '#475569', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Source Sans Pro, sans-serif', body: 'Source Sans Pro, sans-serif', size: { name: '28px', heading: '16px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '4px' }, icons: { show: false, style: 'minimal' } },
    'tech-17': { id: 'tech-17', colors: { primary: '#7c3aed', secondary: '#8b5cf6', accent: '#a78bfa', text: '#1f2937', textLight: '#6b7280', background: '#faf5ff', border: '#e9d5ff' }, fonts: { heading: 'Poppins, sans-serif', body: 'Poppins, sans-serif', size: { name: '30px', heading: '17px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '22px', item: '13px', margin: '44px', padding: '15px' }, layout: { type: 'sidebar', sidebarWidth: '30%', contentWidth: '70%' }, borders: { style: 'solid', width: '1px', radius: '8px' }, icons: { show: true, style: 'outline' } },
    'tech-18': { id: 'tech-18', colors: { primary: '#0284c7', secondary: '#0ea5e9', accent: '#38bdf8', text: '#0f172a', textLight: '#475569', background: '#f0f9ff', border: '#bae6fd' }, fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '2px', radius: '6px' }, icons: { show: true, style: 'outline' } },
    'tech-19': { id: 'tech-19', colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#06b6d4', text: '#334155', textLight: '#64748b', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Outfit, sans-serif', body: 'Outfit, sans-serif', size: { name: '30px', heading: '17px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '22px', item: '13px', margin: '42px', padding: '15px' }, layout: { type: 'minimal', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '4px' }, icons: { show: true, style: 'solid' } },
    'tech-20': { id: 'tech-20', colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#60a5fa', text: '#1e293b', textLight: '#64748b', background: '#f8fafc', border: '#cbd5e1' }, fonts: { heading: 'Roboto, sans-serif', body: 'Roboto, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'double', columns: 2, sidebarWidth: '35%', contentWidth: '65%' }, borders: { style: 'solid', width: '1px', radius: '6px' }, icons: { show: true, style: 'outline' } },

    // CREATIVE 21-30 (10 templates)
    'creative-21': { id: 'creative-21', colors: { primary: '#ec4899', secondary: '#f472b6', accent: '#f9a8d4', text: '#1f2937', textLight: '#6b7280', background: '#fdf2f8', border: '#fbcfe8' }, fonts: { heading: 'Montserrat, sans-serif', body: 'Open Sans, sans-serif', size: { name: '32px', heading: '18px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 800, subheading: 600, body: 400 } }, spacing: { section: '24px', item: '14px', margin: '48px', padding: '16px' }, layout: { type: 'sidebar', sidebarWidth: '35%', contentWidth: '65%' }, borders: { style: 'solid', width: '2px', radius: '8px' }, icons: { show: true, style: 'solid' } },
    'creative-22': { id: 'creative-22', colors: { primary: '#8b5cf6', secondary: '#a78bfa', accent: '#c4b5fd', text: '#1f2937', textLight: '#6b7280', background: '#faf5ff', border: '#e9d5ff' }, fonts: { heading: 'Raleway, sans-serif', body: 'Lato, sans-serif', size: { name: '30px', heading: '17px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '22px', item: '13px', margin: '44px', padding: '15px' }, layout: { type: 'double', columns: 2, sidebarWidth: '40%', contentWidth: '60%' }, borders: { style: 'solid', width: '1px', radius: '10px' }, icons: { show: true, style: 'outline' } },
    'creative-23': { id: 'creative-23', colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#22d3ee', text: '#0f172a', textLight: '#475569', background: '#ecfeff', border: '#a5f3fc' }, fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '2px', radius: '6px' }, icons: { show: true, style: 'outline' } },
    'creative-24': { id: 'creative-24', colors: { primary: '#ea580c', secondary: '#f97316', accent: '#fb923c', text: '#1f2937', textLight: '#6b7280', background: '#fff7ed', border: '#fed7aa' }, fonts: { heading: 'Nunito, sans-serif', body: 'Nunito, sans-serif', size: { name: '30px', heading: '17px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 800, subheading: 600, body: 400 } }, spacing: { section: '22px', item: '13px', margin: '42px', padding: '15px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '8px' }, icons: { show: true, style: 'solid' } },
    'creative-25': { id: 'creative-25', colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#f87171', text: '#1f2937', textLight: '#6b7280', background: '#fef2f2', border: '#fecaca' }, fonts: { heading: 'Quicksand, sans-serif', body: 'Source Sans Pro, sans-serif', size: { name: '32px', heading: '18px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '24px', item: '14px', margin: '48px', padding: '16px' }, layout: { type: 'sidebar', sidebarWidth: '30%', contentWidth: '70%' }, borders: { style: 'solid', width: '2px', radius: '6px' }, icons: { show: true, style: 'outline' } },
    'creative-26': { id: 'creative-26', colors: { primary: '#059669', secondary: '#10b981', accent: '#34d399', text: '#1f2937', textLight: '#6b7280', background: '#f0fdf4', border: '#bbf7d0' }, fonts: { heading: 'Archivo, sans-serif', body: 'Work Sans, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'double', columns: 2, sidebarWidth: '35%', contentWidth: '65%' }, borders: { style: 'solid', width: '1px', radius: '8px' }, icons: { show: true, style: 'outline' } },
    'creative-27': { id: 'creative-27', colors: { primary: '#7c3aed', secondary: '#8b5cf6', accent: '#a78bfa', text: '#1f2937', textLight: '#6b7280', background: '#ffffff', border: '#ddd6fe' }, fonts: { heading: 'Space Grotesk, sans-serif', body: 'Inter, sans-serif', size: { name: '30px', heading: '17px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '22px', item: '13px', margin: '44px', padding: '15px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '2px', radius: '10px' }, icons: { show: true, style: 'solid' } },
    'creative-28': { id: 'creative-28', colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#22d3ee', text: '#0f172a', textLight: '#475569', background: '#f0fdfa', border: '#99f6e4' }, fonts: { heading: 'DM Sans, sans-serif', body: 'DM Sans, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'sidebar', sidebarWidth: '32%', contentWidth: '68%' }, borders: { style: 'solid', width: '1px', radius: '6px' }, icons: { show: true, style: 'outline' } },
    'creative-29': { id: 'creative-29', colors: { primary: '#1f2937', secondary: '#4b5563', accent: '#6b7280', text: '#111827', textLight: '#9ca3af', background: '#ffffff', border: '#e5e7eb' }, fonts: { heading: 'Playfair Display, serif', body: 'Lato, sans-serif', size: { name: '34px', heading: '19px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 300 } }, spacing: { section: '26px', item: '15px', margin: '52px', padding: '17px' }, layout: { type: 'minimal', columns: 1 }, borders: { style: 'solid', width: '0.5px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'creative-30': { id: 'creative-30', colors: { primary: '#000000', secondary: '#1f2937', accent: '#ec4899', text: '#111827', textLight: '#6b7280', background: '#ffffff', border: '#d1d5db' }, fonts: { heading: 'Bebas Neue, sans-serif', body: 'Roboto, sans-serif', size: { name: '36px', heading: '20px', subheading: '15px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '28px', item: '16px', margin: '56px', padding: '18px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '3px', radius: '0px' }, icons: { show: true, style: 'solid' } },

    // ENTRY-LEVEL 31-40 (10 templates)
    'entry-31': { id: 'entry-31', colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#60a5fa', text: '#1f2937', textLight: '#6b7280', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Arial, sans-serif', body: 'Arial, sans-serif', size: { name: '26px', heading: '15px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '18px', item: '10px', margin: '36px', padding: '12px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '2px' }, icons: { show: false, style: 'minimal' } },
    'entry-32': { id: 'entry-32', colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#3b82f6', text: '#334155', textLight: '#64748b', background: '#ffffff', border: '#e2e8f0' }, fonts: { heading: 'Calibri, sans-serif', body: 'Calibri, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'minimal', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'entry-33': { id: 'entry-33', colors: { primary: '#0284c7', secondary: '#0ea5e9', accent: '#38bdf8', text: '#0f172a', textLight: '#475569', background: '#f0f9ff', border: '#bae6fd' }, fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif', size: { name: '26px', heading: '15px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '18px', item: '10px', margin: '36px', padding: '12px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '4px' }, icons: { show: true, style: 'outline' } },
    'entry-34': { id: 'entry-34', colors: { primary: '#000000', secondary: '#374151', accent: '#4b5563', text: '#1f2937', textLight: '#6b7280', background: '#ffffff', border: '#d1d5db' }, fonts: { heading: 'Times New Roman, serif', body: 'Arial, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'entry-35': { id: 'entry-35', colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#60a5fa', text: '#1e293b', textLight: '#64748b', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Roboto, sans-serif', body: 'Roboto, sans-serif', size: { name: '26px', heading: '15px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '18px', item: '10px', margin: '36px', padding: '12px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '2px', radius: '2px' }, icons: { show: false, style: 'minimal' } },
    'entry-36': { id: 'entry-36', colors: { primary: '#0f172a', secondary: '#334155', accent: '#64748b', text: '#1e293b', textLight: '#64748b', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Arial, sans-serif', body: 'Arial, sans-serif', size: { name: '24px', heading: '14px', subheading: '11px', body: '9px', small: '7px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '16px', item: '8px', margin: '32px', padding: '10px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'entry-37': { id: 'entry-37', colors: { primary: '#1e3a8a', secondary: '#1e40af', accent: '#3b82f6', text: '#1f2937', textLight: '#6b7280', background: '#f9fafb', border: '#d1d5db' }, fonts: { heading: 'Georgia, serif', body: 'Arial, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '2px' }, icons: { show: false, style: 'minimal' } },
    'entry-38': { id: 'entry-38', colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#22d3ee', text: '#0f172a', textLight: '#475569', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Open Sans, sans-serif', body: 'Open Sans, sans-serif', size: { name: '26px', heading: '15px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '18px', item: '10px', margin: '36px', padding: '12px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '4px' }, icons: { show: true, style: 'outline' } },
    'entry-39': { id: 'entry-39', colors: { primary: '#6366f1', secondary: '#818cf8', accent: '#a5b4fc', text: '#1f2937', textLight: '#6b7280', background: '#eef2ff', border: '#c7d2fe' }, fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif', size: { name: '26px', heading: '15px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '18px', item: '10px', margin: '36px', padding: '12px' }, layout: { type: 'sidebar', sidebarWidth: '30%', contentWidth: '70%' }, borders: { style: 'solid', width: '1px', radius: '6px' }, icons: { show: true, style: 'outline' } },
    'entry-40': { id: 'entry-40', colors: { primary: '#0284c7', secondary: '#0ea5e9', accent: '#38bdf8', text: '#0f172a', textLight: '#475569', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Roboto, sans-serif', body: 'Roboto, sans-serif', size: { name: '26px', heading: '15px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '18px', item: '10px', margin: '36px', padding: '12px' }, layout: { type: 'minimal', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '2px' }, icons: { show: false, style: 'minimal' } },

    // ACADEMIC 41-45 (5 templates)
    'academic-41': { id: 'academic-41', colors: { primary: '#1e293b', secondary: '#334155', accent: '#475569', text: '#0f172a', textLight: '#64748b', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Times New Roman, serif', body: 'Times New Roman, serif', size: { name: '30px', heading: '17px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '24px', item: '14px', margin: '48px', padding: '16px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'academic-42': { id: 'academic-42', colors: { primary: '#000000', secondary: '#1f2937', accent: '#374151', text: '#111827', textLight: '#6b7280', background: '#ffffff', border: '#d1d5db' }, fonts: { heading: 'Georgia, serif', body: 'Georgia, serif', size: { name: '32px', heading: '18px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '26px', item: '15px', margin: '52px', padding: '17px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'academic-43': { id: 'academic-43', colors: { primary: '#1e3a8a', secondary: '#1e40af', accent: '#3b82f6', text: '#1f2937', textLight: '#6b7280', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Garamond, serif', body: 'Times New Roman, serif', size: { name: '32px', heading: '18px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '24px', item: '14px', margin: '48px', padding: '16px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'academic-44': { id: 'academic-44', colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#334155', text: '#0f172a', textLight: '#475569', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Times New Roman, serif', body: 'Arial, sans-serif', size: { name: '30px', heading: '17px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '24px', item: '14px', margin: '48px', padding: '16px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'academic-45': { id: 'academic-45', colors: { primary: '#1e293b', secondary: '#334155', accent: '#475569', text: '#0f172a', textLight: '#64748b', background: '#f9fafb', border: '#cbd5e1' }, fonts: { heading: 'Palatino, serif', body: 'Times New Roman, serif', size: { name: '32px', heading: '18px', subheading: '14px', body: '11px', small: '9px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '26px', item: '15px', margin: '52px', padding: '17px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },

    // INTERNATIONAL 46-50 (5 templates)
    'intl-46': { id: 'intl-46', colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#60a5fa', text: '#1f2937', textLight: '#6b7280', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Arial, sans-serif', body: 'Arial, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '2px' }, icons: { show: false, style: 'minimal' } },
    'intl-47': { id: 'intl-47', colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#334155', text: '#0f172a', textLight: '#475569', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Calibri, sans-serif', body: 'Calibri, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '0px' }, icons: { show: false, style: 'minimal' } },
    'intl-48': { id: 'intl-48', colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#60a5fa', text: '#1f2937', textLight: '#6b7280', background: '#eff6ff', border: '#bfdbfe' }, fonts: { heading: 'Arial, sans-serif', body: 'Arial, sans-serif', size: { name: '26px', heading: '15px', subheading: '12px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '18px', item: '10px', margin: '36px', padding: '12px' }, layout: { type: 'sidebar', sidebarWidth: '35%', contentWidth: '65%' }, borders: { style: 'solid', width: '1px', radius: '4px' }, icons: { show: true, style: 'outline' } },
    'intl-49': { id: 'intl-49', colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#f87171', text: '#1f2937', textLight: '#6b7280', background: '#ffffff', border: '#cbd5e1' }, fonts: { heading: 'Verdana, sans-serif', body: 'Verdana, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '1px', radius: '2px' }, icons: { show: false, style: 'minimal' } },
    'intl-50': { id: 'intl-50', colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#60a5fa', text: '#1f2937', textLight: '#6b7280', background: '#f0f9ff', border: '#bfdbfe' }, fonts: { heading: 'Arial, sans-serif', body: 'Arial, sans-serif', size: { name: '28px', heading: '16px', subheading: '13px', body: '10px', small: '8px' }, weight: { heading: 700, subheading: 600, body: 400 } }, spacing: { section: '20px', item: '12px', margin: '40px', padding: '14px' }, layout: { type: 'single', columns: 1 }, borders: { style: 'solid', width: '2px', radius: '4px' }, icons: { show: false, style: 'minimal' } },
};

// Combine all configs
export const ALL_TEMPLATE_CONFIGS: Record<string, TemplateConfig> = {
    ...BASE_CONFIGS,
    ...ADDITIONAL_CONFIGS,
};

/**
 * Get template configuration by ID
 */
export function getTemplateConfig(templateId: string): TemplateConfig {
    return ALL_TEMPLATE_CONFIGS[templateId] || ALL_TEMPLATE_CONFIGS['corp-01'];
}

/**
 * Get all available template IDs
 */
export function getAllTemplateIds(): string[] {
    return Object.keys(ALL_TEMPLATE_CONFIGS);
}

/**
 * Get templates by category
 */
export function getTemplatesByCategory(category: 'corp' | 'tech' | 'creative' | 'entry' | 'academic' | 'intl'): string[] {
    return getAllTemplateIds().filter(id => id.startsWith(category));
}

/**
 * Check if template exists
 */
export function templateExists(templateId: string): boolean {
    return templateId in ALL_TEMPLATE_CONFIGS;
}
